[build]
  functions = "functions"

[[redirects]]
  from = "/riot/*"
  to = "/.netlify/functions/riot/:splat"
  status = 200

[[redirects]]
  from = "/br1/*"
  to = "/.netlify/functions/br1/:splat"
  status = 200
