[build]
  publish = "build"
  functions = "functions"

[[redirects]]
  from = "/riot/*"
  to = "/.netlify/functions/riot-proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/br1/*"
  to = "/.netlify/functions/riot-proxy/:splat"
  status = 200
  force = true
